#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web_servers
        balance roundrobin
        server 442641-web-01 54.160.123.27:80
        server 442641-web-02 35.174.209.183:80
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
